import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        heading: ["var(--font-heading)", "serif"],
        headline: ["'Cinzel'", "serif"],
        signature: ["var(--font-signature)", "cursive"],
        body: ["var(--font-body)", "serif"],
        label: ["'Manrope'", "sans-serif"],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
        },
        essenza: {
          blue: "#AFC8D6",
          blueLight: "#C7DCE5",
          gold: "#C9A96E",
          goldLight: "#D8C08A",
          goldDim: "#B99255",
          surface: "#F7F7F5",
          surfaceLow: "#FFFFFF",
          surfaceHigh: "#E8ECE6",
          surfaceVariant: "#DADFD5",
          dark: "#27333B",
          onSurface: "#27333B",
          onSurfaceVariant: "#596B75",
          secondary: "#596B75",
          outline: "#8E9A88",
          outlineVariant: "#DADFD5",
          // Flow-inspired colors
          flow: "#AFC8D6",
          flowLight: "#C7DCE5",
          flowDeep: "#6E8EA1",
          sage: "#AEBFA6",
          sageLight: "#C7D3C0",
          olive: "#AEBFA6",
          oliveDeep: "#6B7B64",
          sand: "#D8C08A",
          cream: "#F7F7F5",
          warmWhite: "#FFFFFF",
        },
        "on-surface": "#27333B",
        "on-surface-variant": "#596B75",
        surface: "#F7F7F5",
        "surface-variant": "#DADFD5",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F7F7F5",
        "surface-container": "#EEF2EF",
        "surface-container-high": "#E8ECE6",
        "surface-container-highest": "#C7D3C0",
        "primary-fixed": "#AFC8D6",
        "primary-fixed-dim": "#D8C08A",
        "on-primary-fixed": "#27333B",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        flowGradient: {
          "0%": { backgroundPosition: "0% 50%" },
          "25%": { backgroundPosition: "50% 100%" },
          "50%": { backgroundPosition: "100% 50%" },
          "75%": { backgroundPosition: "50% 0%" },
          "100%": { backgroundPosition: "0% 50%" },
        },
        breathe: {
          "0%, 100%": { transform: "scale(1)", opacity: "0.6" },
          "50%": { transform: "scale(1.08)", opacity: "0.9" },
        },
        drift: {
          "0%": { transform: "translate(0, 0) scale(1)" },
          "25%": { transform: "translate(30px, -20px) scale(1.05)" },
          "50%": { transform: "translate(-20px, 20px) scale(0.95)" },
          "75%": { transform: "translate(10px, -30px) scale(1.03)" },
          "100%": { transform: "translate(0, 0) scale(1)" },
        },
        wavePulse: {
          "0%, 100%": { transform: "scaleY(1)" },
          "50%": { transform: "scaleY(1.15)" },
        },
        floatSlow: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        float: "float 6s ease-in-out infinite",
        shimmer: "shimmer 3s ease-in-out infinite",
        "flow-gradient": "flowGradient 15s ease infinite",
        breathe: "breathe 6s ease-in-out infinite",
        drift: "drift 20s ease-in-out infinite",
        "drift-slow": "drift 30s ease-in-out infinite",
        "wave-pulse": "wavePulse 8s ease-in-out infinite",
        "float-slow": "floatSlow 8s ease-in-out infinite",
        "float-medium": "floatSlow 5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
